# Base image for Raspberry Pi (all models) (armfh deprecated?)
FROM armhf/ubuntu:16.04				

# Copy DNSMASQ config files 
COPY config/rpiaas-dnsmasq/dnsmasq.conf /etc/dnsmasq.d/ipcluster.conf
COPY config/rpiaas-dnsmasq/dnsmasq_static_hosts /etc/dnsmasq_static_hosts

# Create TFTP boot root directory 
RUN mkdir /tftpboot

# Create volume inside /tftpboot folder
VOLUME ["/tftpboot"]

# Install dnsmasq
RUN apt-get update && apt-get -y install dnsmasq

# No ports required when running in host network mode
# EXPOSE 53/tcp
# EXPOSE 53/udp
# EXPOSE 67
# EXPOSE 67/udp
# EXPOSE 547
# EXPOSE 547/udp
# EXPOSE 647
# EXPOSE 647/udp
# EXPOSE 847
# EXPOSE 847/udp

# Start dnsmasq in foreground, with dhcp broadcasting enabled
CMD ["dnsmasq", "--keep-in-foreground", "--conf-dir=/etc/dnsmasq.d/,*.conf", "--log-facility=-","--dhcp-broadcast"]
