############################################
# Docker compose file for agent node      #
# For agents: see rpiaas-master.yml         #
############################################
version: "2"  # "3" if beta release (swarm mode)
services:
  rpiaas-cas:
    build: 
      context: ../
      dockerfile: docker/rpiaas-cas/Dockerfile_${ARCH}
    ports:
      - "8081:8081"
    volumes:
      - /data:/data
